// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 2awYjQxaFuULphBNfdnqZC
// Component: CeaT0ab-nEDE
import * as React from "react";
import {
  Stack as Stack__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic.module.css"; // plasmic-import: 2awYjQxaFuULphBNfdnqZC/projectcss
import sty from "./PlasmicHomepage.module.css"; // plasmic-import: CeaT0ab-nEDE/css
import Image7Icon from "./icons/PlasmicIcon__Image7"; // plasmic-import: 1Kxn2OSTU49a/icon
import ArrowRightIcon from "./icons/PlasmicIcon__ArrowRight"; // plasmic-import: kjXxvQC9_jlu/icon
import Vector1Icon from "./icons/PlasmicIcon__Vector1"; // plasmic-import: 9EDqbG1ZxSAX/icon
import Calendar2Icon from "./icons/PlasmicIcon__Calendar2"; // plasmic-import: U2ix7DjIvRun/icon
import ClockIcon from "./icons/PlasmicIcon__Clock"; // plasmic-import: fLZaPCGWwjw-/icon
import SearchNormalIcon from "./icons/PlasmicIcon__SearchNormal"; // plasmic-import: T9qCoXYybk8K/icon
import SunIcon from "./icons/PlasmicIcon__Sun"; // plasmic-import: YkyfZiWmVqoo/icon
import ProfileAddIcon from "./icons/PlasmicIcon__ProfileAdd"; // plasmic-import: RHJ4YO7Bu-nu/icon
import Group2Icon from "./icons/PlasmicIcon__Group2"; // plasmic-import: fxC1DD-9gzWf/icon
import HospitalIcon from "./icons/PlasmicIcon__Hospital"; // plasmic-import: _PFvCSmvjxax/icon
import LocationIcon from "./icons/PlasmicIcon__Location"; // plasmic-import: fJXAemdXawkD/icon
import Vector2Icon from "./icons/PlasmicIcon__Vector2"; // plasmic-import: _66_AVX5hDA2/icon
import Clock2Icon from "./icons/PlasmicIcon__Clock2"; // plasmic-import: Wfnv6nGhvbch/icon
import VectorIcon from "./icons/PlasmicIcon__Vector"; // plasmic-import: wMQiFPICzeJi/icon
import Vector3Icon from "./icons/PlasmicIcon__Vector3"; // plasmic-import: 4572UgBPokvw/icon
import GroupIcon from "./icons/PlasmicIcon__Group"; // plasmic-import: UY4UT-4KJyPW/icon
import NotchIcon from "./icons/PlasmicIcon__Notch"; // plasmic-import: a9Pib2l75vm0/icon
import BatteryIcon from "./icons/PlasmicIcon__Battery"; // plasmic-import: 8KnjcNRZ2v8L/icon
import WifiIcon from "./icons/PlasmicIcon__Wifi"; // plasmic-import: wJ8PLsRrnEK8/icon
import MobileSignalIcon from "./icons/PlasmicIcon__MobileSignal"; // plasmic-import: Tw3cQ3JcAbk0/icon
import HomeIcon from "./icons/PlasmicIcon__Home"; // plasmic-import: kDpKzZQFyru8/icon
import Calendar22Icon from "./icons/PlasmicIcon__Calendar22"; // plasmic-import: vFSQagfq1MSF/icon
import MessageIcon from "./icons/PlasmicIcon__Message"; // plasmic-import: OpVPcPNP5aO7/icon
import ProfileIcon from "./icons/PlasmicIcon__Profile"; // plasmic-import: a1-Ji9wEVmkF/icon

createPlasmicElementProxy;

export const PlasmicHomepage__VariantProps = new Array();

export const PlasmicHomepage__ArgProps = new Array();

const $$ = {};

function PlasmicHomepage__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );
  const $props = {
    ...args,
    ...variants
  };
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  return (
    <React.Fragment>
      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <section
            data-plasmic-name={"section"}
            data-plasmic-override={overrides.section}
            className={classNames(projectcss.all, sty.section)}
          >
            <h1
              data-plasmic-name={"h1"}
              data-plasmic-override={overrides.h1}
              className={classNames(
                projectcss.all,
                projectcss.h1,
                projectcss.__wab_text,
                sty.h1
              )}
            >
              {""}
            </h1>
            <div
              data-plasmic-name={"home"}
              data-plasmic-override={overrides.home}
              className={classNames(projectcss.all, sty.home)}
            >
              <Stack__
                as={"div"}
                data-plasmic-name={"frame17"}
                data-plasmic-override={overrides.frame17}
                hasGap={true}
                className={classNames(projectcss.all, sty.frame17)}
              >
                <Stack__
                  as={"div"}
                  data-plasmic-name={"frame24"}
                  data-plasmic-override={overrides.frame24}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.frame24)}
                >
                  <Stack__
                    as={"div"}
                    data-plasmic-name={"frame23"}
                    data-plasmic-override={overrides.frame23}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.frame23)}
                  >
                    <Stack__
                      as={"div"}
                      data-plasmic-name={"frame11"}
                      data-plasmic-override={overrides.frame11}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.frame11)}
                    >
                      <div
                        data-plasmic-name={"frame16"}
                        data-plasmic-override={overrides.frame16}
                        className={classNames(projectcss.all, sty.frame16)}
                      >
                        <Stack__
                          as={"div"}
                          data-plasmic-name={"frame12"}
                          data-plasmic-override={overrides.frame12}
                          hasGap={true}
                          className={classNames(projectcss.all, sty.frame12)}
                        >
                          <div
                            data-plasmic-name={"group1"}
                            data-plasmic-override={overrides.group1}
                            className={classNames(projectcss.all, sty.group1)}
                          >
                            <Image7Icon
                              className={classNames(
                                projectcss.all,
                                sty.svg__dWd
                              )}
                              role={"img"}
                            />

                            <div
                              data-plasmic-name={"maskGroup"}
                              data-plasmic-override={overrides.maskGroup}
                              className={classNames(
                                projectcss.all,
                                sty.maskGroup
                              )}
                            >
                              <div
                                data-plasmic-name={"image8"}
                                data-plasmic-override={overrides.image8}
                                className={classNames(
                                  projectcss.all,
                                  sty.image8
                                )}
                              />
                            </div>
                          </div>
                          <Stack__
                            as={"div"}
                            data-plasmic-name={"frame10"}
                            data-plasmic-override={overrides.frame10}
                            hasGap={true}
                            className={classNames(projectcss.all, sty.frame10)}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__iZgre
                              )}
                            >
                              {"Dr. Imran Syahir"}
                            </div>
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__hyJdI
                              )}
                            >
                              {"General Doctor"}
                            </div>
                          </Stack__>
                        </Stack__>
                        <div
                          data-plasmic-name={"vuesaxLinearArrowRight"}
                          data-plasmic-override={
                            overrides.vuesaxLinearArrowRight
                          }
                          className={classNames(
                            projectcss.all,
                            sty.vuesaxLinearArrowRight
                          )}
                        >
                          <div
                            data-plasmic-name={"vuesaxLinearArrowRight2"}
                            data-plasmic-override={
                              overrides.vuesaxLinearArrowRight2
                            }
                            className={classNames(
                              projectcss.all,
                              sty.vuesaxLinearArrowRight2
                            )}
                          >
                            <ArrowRightIcon
                              className={classNames(
                                projectcss.all,
                                sty.svg__fuOqj
                              )}
                              role={"img"}
                            />
                          </div>
                        </div>
                      </div>
                      <Vector1Icon
                        className={classNames(projectcss.all, sty.svg___3TCeb)}
                        role={"img"}
                      />

                      <Stack__
                        as={"div"}
                        data-plasmic-name={"frame15"}
                        data-plasmic-override={overrides.frame15}
                        hasGap={true}
                        className={classNames(projectcss.all, sty.frame15)}
                      >
                        <Stack__
                          as={"div"}
                          data-plasmic-name={"frame14"}
                          data-plasmic-override={overrides.frame14}
                          hasGap={true}
                          className={classNames(projectcss.all, sty.frame14)}
                        >
                          <div
                            data-plasmic-name={"vuesaxLinearCalendar2"}
                            data-plasmic-override={
                              overrides.vuesaxLinearCalendar2
                            }
                            className={classNames(
                              projectcss.all,
                              sty.vuesaxLinearCalendar2
                            )}
                          >
                            <div
                              data-plasmic-name={"vuesaxLinearCalendar22"}
                              data-plasmic-override={
                                overrides.vuesaxLinearCalendar22
                              }
                              className={classNames(
                                projectcss.all,
                                sty.vuesaxLinearCalendar22
                              )}
                            >
                              <Calendar2Icon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__rrAop
                                )}
                                role={"img"}
                              />
                            </div>
                          </div>
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__jyce9
                            )}
                          >
                            {"Sunday, 12 June"}
                          </div>
                        </Stack__>
                        <Stack__
                          as={"div"}
                          data-plasmic-name={"frame13"}
                          data-plasmic-override={overrides.frame13}
                          hasGap={true}
                          className={classNames(projectcss.all, sty.frame13)}
                        >
                          <div
                            data-plasmic-name={"vuesaxLinearClock"}
                            data-plasmic-override={overrides.vuesaxLinearClock}
                            className={classNames(
                              projectcss.all,
                              sty.vuesaxLinearClock
                            )}
                          >
                            <div
                              data-plasmic-name={"vuesaxLinearClock2"}
                              data-plasmic-override={
                                overrides.vuesaxLinearClock2
                              }
                              className={classNames(
                                projectcss.all,
                                sty.vuesaxLinearClock2
                              )}
                            >
                              <ClockIcon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__t2UK
                                )}
                                role={"img"}
                              />
                            </div>
                          </div>
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__cEfWp
                            )}
                          >
                            {"11:00 - 12:00 AM"}
                          </div>
                        </Stack__>
                      </Stack__>
                    </Stack__>
                    <Stack__
                      as={"div"}
                      data-plasmic-name={"frame9"}
                      data-plasmic-override={overrides.frame9}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.frame9)}
                    >
                      <div
                        data-plasmic-name={"vuesaxLinearSearchNormal"}
                        data-plasmic-override={
                          overrides.vuesaxLinearSearchNormal
                        }
                        className={classNames(
                          projectcss.all,
                          sty.vuesaxLinearSearchNormal
                        )}
                      >
                        <div
                          data-plasmic-name={"vuesaxLinearSearchNormal2"}
                          data-plasmic-override={
                            overrides.vuesaxLinearSearchNormal2
                          }
                          className={classNames(
                            projectcss.all,
                            sty.vuesaxLinearSearchNormal2
                          )}
                        >
                          <SearchNormalIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg___6RJFu
                            )}
                            role={"img"}
                          />
                        </div>
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__js6J
                        )}
                      >
                        {"Search doctor or health issue"}
                      </div>
                    </Stack__>
                  </Stack__>
                  <Stack__
                    as={"div"}
                    data-plasmic-name={"frame22"}
                    data-plasmic-override={overrides.frame22}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.frame22)}
                  >
                    <Stack__
                      as={"div"}
                      data-plasmic-name={"frame18"}
                      data-plasmic-override={overrides.frame18}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.frame18)}
                    >
                      <Stack__
                        as={"div"}
                        data-plasmic-name={"vuesaxBoldSun"}
                        data-plasmic-override={overrides.vuesaxBoldSun}
                        hasGap={true}
                        className={classNames(
                          projectcss.all,
                          sty.vuesaxBoldSun
                        )}
                      >
                        <div
                          data-plasmic-name={"vuesaxBoldSun2"}
                          data-plasmic-override={overrides.vuesaxBoldSun2}
                          className={classNames(
                            projectcss.all,
                            sty.vuesaxBoldSun2
                          )}
                        >
                          <SunIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__di8V
                            )}
                            role={"img"}
                          />
                        </div>
                      </Stack__>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__x1HYs
                        )}
                      >
                        {"Covid 19"}
                      </div>
                    </Stack__>
                    <Stack__
                      as={"div"}
                      data-plasmic-name={"frame19"}
                      data-plasmic-override={overrides.frame19}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.frame19)}
                    >
                      <Stack__
                        as={"div"}
                        data-plasmic-name={"vuesaxBoldProfileAdd"}
                        data-plasmic-override={overrides.vuesaxBoldProfileAdd}
                        hasGap={true}
                        className={classNames(
                          projectcss.all,
                          sty.vuesaxBoldProfileAdd
                        )}
                      >
                        <div
                          data-plasmic-name={"vuesaxBoldProfileAdd2"}
                          data-plasmic-override={
                            overrides.vuesaxBoldProfileAdd2
                          }
                          className={classNames(
                            projectcss.all,
                            sty.vuesaxBoldProfileAdd2
                          )}
                        >
                          <ProfileAddIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__yo6Qa
                            )}
                            role={"img"}
                          />
                        </div>
                      </Stack__>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__uze9X
                        )}
                      >
                        {"Doctor"}
                      </div>
                    </Stack__>
                    <Stack__
                      as={"div"}
                      data-plasmic-name={"frame20"}
                      data-plasmic-override={overrides.frame20}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.frame20)}
                    >
                      <Stack__
                        as={"div"}
                        data-plasmic-name={"vuesaxBoldLink"}
                        data-plasmic-override={overrides.vuesaxBoldLink}
                        hasGap={true}
                        className={classNames(
                          projectcss.all,
                          sty.vuesaxBoldLink
                        )}
                      >
                        <div
                          data-plasmic-name={"vuesaxBoldLink2"}
                          data-plasmic-override={overrides.vuesaxBoldLink2}
                          className={classNames(
                            projectcss.all,
                            sty.vuesaxBoldLink2
                          )}
                        >
                          <div
                            data-plasmic-name={"link"}
                            data-plasmic-override={overrides.link}
                            className={classNames(projectcss.all, sty.link)}
                          >
                            <Group2Icon
                              className={classNames(
                                projectcss.all,
                                sty.svg___6GxwB
                              )}
                              role={"img"}
                            />
                          </div>
                        </div>
                      </Stack__>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__a3Wrh
                        )}
                      >
                        {"Medicine"}
                      </div>
                    </Stack__>
                    <Stack__
                      as={"div"}
                      data-plasmic-name={"frame21"}
                      data-plasmic-override={overrides.frame21}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.frame21)}
                    >
                      <Stack__
                        as={"div"}
                        data-plasmic-name={"vuesaxBoldHospital"}
                        data-plasmic-override={overrides.vuesaxBoldHospital}
                        hasGap={true}
                        className={classNames(
                          projectcss.all,
                          sty.vuesaxBoldHospital
                        )}
                      >
                        <div
                          data-plasmic-name={"vuesaxBoldHospital2"}
                          data-plasmic-override={overrides.vuesaxBoldHospital2}
                          className={classNames(
                            projectcss.all,
                            sty.vuesaxBoldHospital2
                          )}
                        >
                          <HospitalIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg___8MGg
                            )}
                            role={"img"}
                          />
                        </div>
                      </Stack__>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__hVjza
                        )}
                      >
                        {"Hospital"}
                      </div>
                    </Stack__>
                  </Stack__>
                </Stack__>
                <Stack__
                  as={"div"}
                  data-plasmic-name={"frame25"}
                  data-plasmic-override={overrides.frame25}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.frame25)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__wUIlK
                    )}
                  >
                    {"Near Doctor"}
                  </div>
                  <div
                    data-plasmic-name={"frame33"}
                    data-plasmic-override={overrides.frame33}
                    className={classNames(projectcss.all, sty.frame33)}
                  >
                    <Stack__
                      as={"div"}
                      data-plasmic-name={"frame26"}
                      data-plasmic-override={overrides.frame26}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.frame26)}
                    >
                      <Stack__
                        as={"div"}
                        data-plasmic-name={"frame29"}
                        data-plasmic-override={overrides.frame29}
                        hasGap={true}
                        className={classNames(projectcss.all, sty.frame29)}
                      >
                        <Stack__
                          as={"div"}
                          data-plasmic-name={"frame27"}
                          data-plasmic-override={overrides.frame27}
                          hasGap={true}
                          className={classNames(projectcss.all, sty.frame27)}
                        >
                          <div
                            data-plasmic-name={"group2"}
                            data-plasmic-override={overrides.group2}
                            className={classNames(projectcss.all, sty.group2)}
                          >
                            <Image7Icon
                              className={classNames(
                                projectcss.all,
                                sty.svg__xsccZ
                              )}
                              role={"img"}
                            />

                            <div
                              data-plasmic-name={"maskGroup2"}
                              data-plasmic-override={overrides.maskGroup2}
                              className={classNames(
                                projectcss.all,
                                sty.maskGroup2
                              )}
                            >
                              <div
                                data-plasmic-name={"image9"}
                                data-plasmic-override={overrides.image9}
                                className={classNames(
                                  projectcss.all,
                                  sty.image9
                                )}
                              />
                            </div>
                          </div>
                          <Stack__
                            as={"div"}
                            data-plasmic-name={"frame28"}
                            data-plasmic-override={overrides.frame28}
                            hasGap={true}
                            className={classNames(projectcss.all, sty.frame28)}
                          >
                            <Stack__
                              as={"div"}
                              data-plasmic-name={"frame30"}
                              data-plasmic-override={overrides.frame30}
                              hasGap={true}
                              className={classNames(
                                projectcss.all,
                                sty.frame30
                              )}
                            >
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text___7YVW
                                )}
                              >
                                {"Dr. Imran Syahir"}
                              </div>
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text__ogtsp
                                )}
                              >
                                {"General Doctor"}
                              </div>
                            </Stack__>
                          </Stack__>
                        </Stack__>
                        <Stack__
                          as={"div"}
                          data-plasmic-name={"frame32"}
                          data-plasmic-override={overrides.frame32}
                          hasGap={true}
                          className={classNames(projectcss.all, sty.frame32)}
                        >
                          <div
                            data-plasmic-name={"vuesaxLinearLocation"}
                            data-plasmic-override={
                              overrides.vuesaxLinearLocation
                            }
                            className={classNames(
                              projectcss.all,
                              sty.vuesaxLinearLocation
                            )}
                          >
                            <div
                              data-plasmic-name={"vuesaxLinearLocation2"}
                              data-plasmic-override={
                                overrides.vuesaxLinearLocation2
                              }
                              className={classNames(
                                projectcss.all,
                                sty.vuesaxLinearLocation2
                              )}
                            >
                              <LocationIcon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__ezO7V
                                )}
                                role={"img"}
                              />
                            </div>
                          </div>
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__qqyV4
                            )}
                          >
                            {"1.2 KM"}
                          </div>
                        </Stack__>
                      </Stack__>
                      <Vector2Icon
                        className={classNames(projectcss.all, sty.svg__qdJkE)}
                        role={"img"}
                      />

                      <Stack__
                        as={"div"}
                        data-plasmic-name={"frame31"}
                        data-plasmic-override={overrides.frame31}
                        hasGap={true}
                        className={classNames(projectcss.all, sty.frame31)}
                      >
                        <Stack__
                          as={"div"}
                          data-plasmic-name={"frame34"}
                          data-plasmic-override={overrides.frame34}
                          hasGap={true}
                          className={classNames(projectcss.all, sty.frame34)}
                        >
                          <div
                            data-plasmic-name={"vuesaxLinearClock3"}
                            data-plasmic-override={overrides.vuesaxLinearClock3}
                            className={classNames(
                              projectcss.all,
                              sty.vuesaxLinearClock3
                            )}
                          >
                            <div
                              data-plasmic-name={"vuesaxLinearClock4"}
                              data-plasmic-override={
                                overrides.vuesaxLinearClock4
                              }
                              className={classNames(
                                projectcss.all,
                                sty.vuesaxLinearClock4
                              )}
                            >
                              <Clock2Icon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__ssyfH
                                )}
                                role={"img"}
                              />
                            </div>
                          </div>
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__zXZ
                            )}
                          >
                            {"Open at 17.00"}
                          </div>
                        </Stack__>
                        <Stack__
                          as={"div"}
                          data-plasmic-name={"frame35"}
                          data-plasmic-override={overrides.frame35}
                          hasGap={true}
                          className={classNames(projectcss.all, sty.frame35)}
                        >
                          <div
                            data-plasmic-name={"vuesaxLinearClock5"}
                            data-plasmic-override={overrides.vuesaxLinearClock5}
                            className={classNames(
                              projectcss.all,
                              sty.vuesaxLinearClock5
                            )}
                          >
                            <div
                              data-plasmic-name={"vuesaxLinearClock6"}
                              data-plasmic-override={
                                overrides.vuesaxLinearClock6
                              }
                              className={classNames(
                                projectcss.all,
                                sty.vuesaxLinearClock6
                              )}
                            >
                              <Clock2Icon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg___853Tc
                                )}
                                role={"img"}
                              />
                            </div>
                          </div>
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__mK77T
                            )}
                          >
                            {"4,8 (120 Reviews)"}
                          </div>
                        </Stack__>
                      </Stack__>
                    </Stack__>
                    <Stack__
                      as={"div"}
                      data-plasmic-name={"frame36"}
                      data-plasmic-override={overrides.frame36}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.frame36)}
                    >
                      <Stack__
                        as={"div"}
                        data-plasmic-name={"frame37"}
                        data-plasmic-override={overrides.frame37}
                        hasGap={true}
                        className={classNames(projectcss.all, sty.frame37)}
                      >
                        <Stack__
                          as={"div"}
                          data-plasmic-name={"frame38"}
                          data-plasmic-override={overrides.frame38}
                          hasGap={true}
                          className={classNames(projectcss.all, sty.frame38)}
                        >
                          <div
                            data-plasmic-name={"group3"}
                            data-plasmic-override={overrides.group3}
                            className={classNames(projectcss.all, sty.group3)}
                          >
                            <Image7Icon
                              className={classNames(
                                projectcss.all,
                                sty.svg__sDPbi
                              )}
                              role={"img"}
                            />

                            <div
                              data-plasmic-name={"maskGroup3"}
                              data-plasmic-override={overrides.maskGroup3}
                              className={classNames(
                                projectcss.all,
                                sty.maskGroup3
                              )}
                            >
                              <div
                                data-plasmic-name={"image10"}
                                data-plasmic-override={overrides.image10}
                                className={classNames(
                                  projectcss.all,
                                  sty.image10
                                )}
                              />
                            </div>
                          </div>
                          <Stack__
                            as={"div"}
                            data-plasmic-name={"frame39"}
                            data-plasmic-override={overrides.frame39}
                            hasGap={true}
                            className={classNames(projectcss.all, sty.frame39)}
                          >
                            <Stack__
                              as={"div"}
                              data-plasmic-name={"frame40"}
                              data-plasmic-override={overrides.frame40}
                              hasGap={true}
                              className={classNames(
                                projectcss.all,
                                sty.frame40
                              )}
                            >
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text__vxVzo
                                )}
                              >
                                {"Dr. Joseph Brostito"}
                              </div>
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text__cpVqc
                                )}
                              >
                                {"Dental Specialist"}
                              </div>
                            </Stack__>
                          </Stack__>
                        </Stack__>
                        <Stack__
                          as={"div"}
                          data-plasmic-name={"frame41"}
                          data-plasmic-override={overrides.frame41}
                          hasGap={true}
                          className={classNames(projectcss.all, sty.frame41)}
                        >
                          <div
                            data-plasmic-name={"vuesaxLinearLocation3"}
                            data-plasmic-override={
                              overrides.vuesaxLinearLocation3
                            }
                            className={classNames(
                              projectcss.all,
                              sty.vuesaxLinearLocation3
                            )}
                          >
                            <div
                              data-plasmic-name={"vuesaxLinearLocation4"}
                              data-plasmic-override={
                                overrides.vuesaxLinearLocation4
                              }
                              className={classNames(
                                projectcss.all,
                                sty.vuesaxLinearLocation4
                              )}
                            >
                              <LocationIcon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__jbyq7
                                )}
                                role={"img"}
                              />
                            </div>
                          </div>
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__rTftU
                            )}
                          >
                            {"1.2 KM"}
                          </div>
                        </Stack__>
                      </Stack__>
                      <Vector2Icon
                        className={classNames(projectcss.all, sty.svg__r6GeR)}
                        role={"img"}
                      />

                      <Stack__
                        as={"div"}
                        data-plasmic-name={"frame42"}
                        data-plasmic-override={overrides.frame42}
                        hasGap={true}
                        className={classNames(projectcss.all, sty.frame42)}
                      >
                        <Stack__
                          as={"div"}
                          data-plasmic-name={"frame43"}
                          data-plasmic-override={overrides.frame43}
                          hasGap={true}
                          className={classNames(projectcss.all, sty.frame43)}
                        >
                          <div
                            data-plasmic-name={"vuesaxLinearClock7"}
                            data-plasmic-override={overrides.vuesaxLinearClock7}
                            className={classNames(
                              projectcss.all,
                              sty.vuesaxLinearClock7
                            )}
                          >
                            <div
                              data-plasmic-name={"vuesaxLinearClock8"}
                              data-plasmic-override={
                                overrides.vuesaxLinearClock8
                              }
                              className={classNames(
                                projectcss.all,
                                sty.vuesaxLinearClock8
                              )}
                            >
                              <Clock2Icon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__kIwM
                                )}
                                role={"img"}
                              />
                            </div>
                          </div>
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__l72Zd
                            )}
                          >
                            {"4,8 (120 Reviews)"}
                          </div>
                        </Stack__>
                        <Stack__
                          as={"div"}
                          data-plasmic-name={"frame44"}
                          data-plasmic-override={overrides.frame44}
                          hasGap={true}
                          className={classNames(projectcss.all, sty.frame44)}
                        >
                          <div
                            data-plasmic-name={"vuesaxLinearClock9"}
                            data-plasmic-override={overrides.vuesaxLinearClock9}
                            className={classNames(
                              projectcss.all,
                              sty.vuesaxLinearClock9
                            )}
                          >
                            <div
                              data-plasmic-name={"vuesaxLinearClock10"}
                              data-plasmic-override={
                                overrides.vuesaxLinearClock10
                              }
                              className={classNames(
                                projectcss.all,
                                sty.vuesaxLinearClock10
                              )}
                            >
                              <Clock2Icon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__aUxug
                                )}
                                role={"img"}
                              />
                            </div>
                          </div>
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__yDn8N
                            )}
                          >
                            {"Open at 17.00"}
                          </div>
                        </Stack__>
                      </Stack__>
                    </Stack__>
                  </div>
                </Stack__>
              </Stack__>
              <Stack__
                as={"div"}
                data-plasmic-name={"frame8"}
                data-plasmic-override={overrides.frame8}
                hasGap={true}
                className={classNames(projectcss.all, sty.frame8)}
              >
                <Stack__
                  as={"div"}
                  data-plasmic-name={"frame7"}
                  data-plasmic-override={overrides.frame7}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.frame7)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__dvVbm
                    )}
                  >
                    {"Hello,"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__rrnl7
                    )}
                  >
                    {"Hi James"}
                  </div>
                </Stack__>
                <div
                  data-plasmic-name={"frame"}
                  data-plasmic-override={overrides.frame}
                  className={classNames(projectcss.all, sty.frame)}
                >
                  <div
                    data-plasmic-name={"group"}
                    data-plasmic-override={overrides.group}
                    className={classNames(projectcss.all, sty.group)}
                  >
                    <VectorIcon
                      className={classNames(projectcss.all, sty.svg___0ZcW4)}
                      role={"img"}
                    />

                    <Vector3Icon
                      className={classNames(projectcss.all, sty.svg__cpR1M)}
                      role={"img"}
                    />

                    <GroupIcon
                      className={classNames(projectcss.all, sty.svg__um2AS)}
                      role={"img"}
                    />
                  </div>
                </div>
              </Stack__>
              <div
                data-plasmic-name={"statusBarIPhone1313Pro"}
                data-plasmic-override={overrides.statusBarIPhone1313Pro}
                className={classNames(
                  projectcss.all,
                  sty.statusBarIPhone1313Pro
                )}
              >
                {false ? (
                  <NotchIcon
                    className={classNames(projectcss.all, sty.svg__a6LpZ)}
                    role={"img"}
                  />
                ) : null}
                <div
                  data-plasmic-name={"rightSide"}
                  data-plasmic-override={overrides.rightSide}
                  className={classNames(projectcss.all, sty.rightSide)}
                >
                  <BatteryIcon
                    className={classNames(projectcss.all, sty.svg__tz2Qt)}
                    role={"img"}
                  />

                  <WifiIcon
                    className={classNames(projectcss.all, sty.svg___8ZRvH)}
                    role={"img"}
                  />

                  <MobileSignalIcon
                    className={classNames(projectcss.all, sty.svg___2HasX)}
                    role={"img"}
                  />
                </div>
                <div
                  data-plasmic-name={"leftSide"}
                  data-plasmic-override={overrides.leftSide}
                  className={classNames(projectcss.all, sty.leftSide)}
                >
                  <div
                    data-plasmic-name={"time"}
                    data-plasmic-override={overrides.time}
                    className={classNames(projectcss.all, sty.time)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__b5F0B
                      )}
                    >
                      {"9:41"}
                    </div>
                  </div>
                </div>
              </div>
              <Stack__
                as={"div"}
                data-plasmic-name={"frame6"}
                data-plasmic-override={overrides.frame6}
                hasGap={true}
                className={classNames(projectcss.all, sty.frame6)}
              >
                <Stack__
                  as={"div"}
                  data-plasmic-name={"frame1"}
                  data-plasmic-override={overrides.frame1}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.frame1)}
                >
                  <div
                    data-plasmic-name={"home2"}
                    data-plasmic-override={overrides.home2}
                    className={classNames(projectcss.all, sty.home2)}
                  >
                    <div
                      data-plasmic-name={"home3"}
                      data-plasmic-override={overrides.home3}
                      className={classNames(projectcss.all, sty.home3)}
                    >
                      <HomeIcon
                        className={classNames(projectcss.all, sty.svg__jdLcU)}
                        role={"img"}
                      />
                    </div>
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__uu25F
                    )}
                  >
                    {"Home"}
                  </div>
                </Stack__>
                <Stack__
                  as={"div"}
                  data-plasmic-name={"frame4"}
                  data-plasmic-override={overrides.frame4}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.frame4)}
                >
                  <div
                    data-plasmic-name={"vuesaxLinearCalendar23"}
                    data-plasmic-override={overrides.vuesaxLinearCalendar23}
                    className={classNames(
                      projectcss.all,
                      sty.vuesaxLinearCalendar23
                    )}
                  >
                    <div
                      data-plasmic-name={"vuesaxLinearCalendar24"}
                      data-plasmic-override={overrides.vuesaxLinearCalendar24}
                      className={classNames(
                        projectcss.all,
                        sty.vuesaxLinearCalendar24
                      )}
                    >
                      <Calendar22Icon
                        className={classNames(projectcss.all, sty.svg__mkldb)}
                        role={"img"}
                      />
                    </div>
                  </div>
                </Stack__>
                <Stack__
                  as={"div"}
                  data-plasmic-name={"frame5"}
                  data-plasmic-override={overrides.frame5}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.frame5)}
                >
                  <div
                    data-plasmic-name={"vuesaxLinearMessage"}
                    data-plasmic-override={overrides.vuesaxLinearMessage}
                    className={classNames(
                      projectcss.all,
                      sty.vuesaxLinearMessage
                    )}
                  >
                    <div
                      data-plasmic-name={"vuesaxLinearMessage2"}
                      data-plasmic-override={overrides.vuesaxLinearMessage2}
                      className={classNames(
                        projectcss.all,
                        sty.vuesaxLinearMessage2
                      )}
                    >
                      <MessageIcon
                        className={classNames(projectcss.all, sty.svg__f2MSe)}
                        role={"img"}
                      />
                    </div>
                  </div>
                </Stack__>
                <Stack__
                  as={"div"}
                  data-plasmic-name={"frame3"}
                  data-plasmic-override={overrides.frame3}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.frame3)}
                >
                  <div
                    data-plasmic-name={"vuesaxLinearProfile"}
                    data-plasmic-override={overrides.vuesaxLinearProfile}
                    className={classNames(
                      projectcss.all,
                      sty.vuesaxLinearProfile
                    )}
                  >
                    <div
                      data-plasmic-name={"vuesaxLinearProfile2"}
                      data-plasmic-override={overrides.vuesaxLinearProfile2}
                      className={classNames(
                        projectcss.all,
                        sty.vuesaxLinearProfile2
                      )}
                    >
                      <ProfileIcon
                        className={classNames(projectcss.all, sty.svg___8HMNd)}
                        role={"img"}
                      />
                    </div>
                  </div>
                </Stack__>
              </Stack__>
            </div>
          </section>
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "section",
    "h1",
    "home",
    "frame17",
    "frame24",
    "frame23",
    "frame11",
    "frame16",
    "frame12",
    "group1",
    "maskGroup",
    "image8",
    "frame10",
    "vuesaxLinearArrowRight",
    "vuesaxLinearArrowRight2",
    "frame15",
    "frame14",
    "vuesaxLinearCalendar2",
    "vuesaxLinearCalendar22",
    "frame13",
    "vuesaxLinearClock",
    "vuesaxLinearClock2",
    "frame9",
    "vuesaxLinearSearchNormal",
    "vuesaxLinearSearchNormal2",
    "frame22",
    "frame18",
    "vuesaxBoldSun",
    "vuesaxBoldSun2",
    "frame19",
    "vuesaxBoldProfileAdd",
    "vuesaxBoldProfileAdd2",
    "frame20",
    "vuesaxBoldLink",
    "vuesaxBoldLink2",
    "link",
    "frame21",
    "vuesaxBoldHospital",
    "vuesaxBoldHospital2",
    "frame25",
    "frame33",
    "frame26",
    "frame29",
    "frame27",
    "group2",
    "maskGroup2",
    "image9",
    "frame28",
    "frame30",
    "frame32",
    "vuesaxLinearLocation",
    "vuesaxLinearLocation2",
    "frame31",
    "frame34",
    "vuesaxLinearClock3",
    "vuesaxLinearClock4",
    "frame35",
    "vuesaxLinearClock5",
    "vuesaxLinearClock6",
    "frame36",
    "frame37",
    "frame38",
    "group3",
    "maskGroup3",
    "image10",
    "frame39",
    "frame40",
    "frame41",
    "vuesaxLinearLocation3",
    "vuesaxLinearLocation4",
    "frame42",
    "frame43",
    "vuesaxLinearClock7",
    "vuesaxLinearClock8",
    "frame44",
    "vuesaxLinearClock9",
    "vuesaxLinearClock10",
    "frame8",
    "frame7",
    "frame",
    "group",
    "statusBarIPhone1313Pro",
    "rightSide",
    "leftSide",
    "time",
    "frame6",
    "frame1",
    "home2",
    "home3",
    "frame4",
    "vuesaxLinearCalendar23",
    "vuesaxLinearCalendar24",
    "frame5",
    "vuesaxLinearMessage",
    "vuesaxLinearMessage2",
    "frame3",
    "vuesaxLinearProfile",
    "vuesaxLinearProfile2"
  ],

  section: [
    "section",
    "h1",
    "home",
    "frame17",
    "frame24",
    "frame23",
    "frame11",
    "frame16",
    "frame12",
    "group1",
    "maskGroup",
    "image8",
    "frame10",
    "vuesaxLinearArrowRight",
    "vuesaxLinearArrowRight2",
    "frame15",
    "frame14",
    "vuesaxLinearCalendar2",
    "vuesaxLinearCalendar22",
    "frame13",
    "vuesaxLinearClock",
    "vuesaxLinearClock2",
    "frame9",
    "vuesaxLinearSearchNormal",
    "vuesaxLinearSearchNormal2",
    "frame22",
    "frame18",
    "vuesaxBoldSun",
    "vuesaxBoldSun2",
    "frame19",
    "vuesaxBoldProfileAdd",
    "vuesaxBoldProfileAdd2",
    "frame20",
    "vuesaxBoldLink",
    "vuesaxBoldLink2",
    "link",
    "frame21",
    "vuesaxBoldHospital",
    "vuesaxBoldHospital2",
    "frame25",
    "frame33",
    "frame26",
    "frame29",
    "frame27",
    "group2",
    "maskGroup2",
    "image9",
    "frame28",
    "frame30",
    "frame32",
    "vuesaxLinearLocation",
    "vuesaxLinearLocation2",
    "frame31",
    "frame34",
    "vuesaxLinearClock3",
    "vuesaxLinearClock4",
    "frame35",
    "vuesaxLinearClock5",
    "vuesaxLinearClock6",
    "frame36",
    "frame37",
    "frame38",
    "group3",
    "maskGroup3",
    "image10",
    "frame39",
    "frame40",
    "frame41",
    "vuesaxLinearLocation3",
    "vuesaxLinearLocation4",
    "frame42",
    "frame43",
    "vuesaxLinearClock7",
    "vuesaxLinearClock8",
    "frame44",
    "vuesaxLinearClock9",
    "vuesaxLinearClock10",
    "frame8",
    "frame7",
    "frame",
    "group",
    "statusBarIPhone1313Pro",
    "rightSide",
    "leftSide",
    "time",
    "frame6",
    "frame1",
    "home2",
    "home3",
    "frame4",
    "vuesaxLinearCalendar23",
    "vuesaxLinearCalendar24",
    "frame5",
    "vuesaxLinearMessage",
    "vuesaxLinearMessage2",
    "frame3",
    "vuesaxLinearProfile",
    "vuesaxLinearProfile2"
  ],

  h1: ["h1"],
  home: [
    "home",
    "frame17",
    "frame24",
    "frame23",
    "frame11",
    "frame16",
    "frame12",
    "group1",
    "maskGroup",
    "image8",
    "frame10",
    "vuesaxLinearArrowRight",
    "vuesaxLinearArrowRight2",
    "frame15",
    "frame14",
    "vuesaxLinearCalendar2",
    "vuesaxLinearCalendar22",
    "frame13",
    "vuesaxLinearClock",
    "vuesaxLinearClock2",
    "frame9",
    "vuesaxLinearSearchNormal",
    "vuesaxLinearSearchNormal2",
    "frame22",
    "frame18",
    "vuesaxBoldSun",
    "vuesaxBoldSun2",
    "frame19",
    "vuesaxBoldProfileAdd",
    "vuesaxBoldProfileAdd2",
    "frame20",
    "vuesaxBoldLink",
    "vuesaxBoldLink2",
    "link",
    "frame21",
    "vuesaxBoldHospital",
    "vuesaxBoldHospital2",
    "frame25",
    "frame33",
    "frame26",
    "frame29",
    "frame27",
    "group2",
    "maskGroup2",
    "image9",
    "frame28",
    "frame30",
    "frame32",
    "vuesaxLinearLocation",
    "vuesaxLinearLocation2",
    "frame31",
    "frame34",
    "vuesaxLinearClock3",
    "vuesaxLinearClock4",
    "frame35",
    "vuesaxLinearClock5",
    "vuesaxLinearClock6",
    "frame36",
    "frame37",
    "frame38",
    "group3",
    "maskGroup3",
    "image10",
    "frame39",
    "frame40",
    "frame41",
    "vuesaxLinearLocation3",
    "vuesaxLinearLocation4",
    "frame42",
    "frame43",
    "vuesaxLinearClock7",
    "vuesaxLinearClock8",
    "frame44",
    "vuesaxLinearClock9",
    "vuesaxLinearClock10",
    "frame8",
    "frame7",
    "frame",
    "group",
    "statusBarIPhone1313Pro",
    "rightSide",
    "leftSide",
    "time",
    "frame6",
    "frame1",
    "home2",
    "home3",
    "frame4",
    "vuesaxLinearCalendar23",
    "vuesaxLinearCalendar24",
    "frame5",
    "vuesaxLinearMessage",
    "vuesaxLinearMessage2",
    "frame3",
    "vuesaxLinearProfile",
    "vuesaxLinearProfile2"
  ],

  frame17: [
    "frame17",
    "frame24",
    "frame23",
    "frame11",
    "frame16",
    "frame12",
    "group1",
    "maskGroup",
    "image8",
    "frame10",
    "vuesaxLinearArrowRight",
    "vuesaxLinearArrowRight2",
    "frame15",
    "frame14",
    "vuesaxLinearCalendar2",
    "vuesaxLinearCalendar22",
    "frame13",
    "vuesaxLinearClock",
    "vuesaxLinearClock2",
    "frame9",
    "vuesaxLinearSearchNormal",
    "vuesaxLinearSearchNormal2",
    "frame22",
    "frame18",
    "vuesaxBoldSun",
    "vuesaxBoldSun2",
    "frame19",
    "vuesaxBoldProfileAdd",
    "vuesaxBoldProfileAdd2",
    "frame20",
    "vuesaxBoldLink",
    "vuesaxBoldLink2",
    "link",
    "frame21",
    "vuesaxBoldHospital",
    "vuesaxBoldHospital2",
    "frame25",
    "frame33",
    "frame26",
    "frame29",
    "frame27",
    "group2",
    "maskGroup2",
    "image9",
    "frame28",
    "frame30",
    "frame32",
    "vuesaxLinearLocation",
    "vuesaxLinearLocation2",
    "frame31",
    "frame34",
    "vuesaxLinearClock3",
    "vuesaxLinearClock4",
    "frame35",
    "vuesaxLinearClock5",
    "vuesaxLinearClock6",
    "frame36",
    "frame37",
    "frame38",
    "group3",
    "maskGroup3",
    "image10",
    "frame39",
    "frame40",
    "frame41",
    "vuesaxLinearLocation3",
    "vuesaxLinearLocation4",
    "frame42",
    "frame43",
    "vuesaxLinearClock7",
    "vuesaxLinearClock8",
    "frame44",
    "vuesaxLinearClock9",
    "vuesaxLinearClock10"
  ],

  frame24: [
    "frame24",
    "frame23",
    "frame11",
    "frame16",
    "frame12",
    "group1",
    "maskGroup",
    "image8",
    "frame10",
    "vuesaxLinearArrowRight",
    "vuesaxLinearArrowRight2",
    "frame15",
    "frame14",
    "vuesaxLinearCalendar2",
    "vuesaxLinearCalendar22",
    "frame13",
    "vuesaxLinearClock",
    "vuesaxLinearClock2",
    "frame9",
    "vuesaxLinearSearchNormal",
    "vuesaxLinearSearchNormal2",
    "frame22",
    "frame18",
    "vuesaxBoldSun",
    "vuesaxBoldSun2",
    "frame19",
    "vuesaxBoldProfileAdd",
    "vuesaxBoldProfileAdd2",
    "frame20",
    "vuesaxBoldLink",
    "vuesaxBoldLink2",
    "link",
    "frame21",
    "vuesaxBoldHospital",
    "vuesaxBoldHospital2"
  ],

  frame23: [
    "frame23",
    "frame11",
    "frame16",
    "frame12",
    "group1",
    "maskGroup",
    "image8",
    "frame10",
    "vuesaxLinearArrowRight",
    "vuesaxLinearArrowRight2",
    "frame15",
    "frame14",
    "vuesaxLinearCalendar2",
    "vuesaxLinearCalendar22",
    "frame13",
    "vuesaxLinearClock",
    "vuesaxLinearClock2",
    "frame9",
    "vuesaxLinearSearchNormal",
    "vuesaxLinearSearchNormal2"
  ],

  frame11: [
    "frame11",
    "frame16",
    "frame12",
    "group1",
    "maskGroup",
    "image8",
    "frame10",
    "vuesaxLinearArrowRight",
    "vuesaxLinearArrowRight2",
    "frame15",
    "frame14",
    "vuesaxLinearCalendar2",
    "vuesaxLinearCalendar22",
    "frame13",
    "vuesaxLinearClock",
    "vuesaxLinearClock2"
  ],

  frame16: [
    "frame16",
    "frame12",
    "group1",
    "maskGroup",
    "image8",
    "frame10",
    "vuesaxLinearArrowRight",
    "vuesaxLinearArrowRight2"
  ],

  frame12: ["frame12", "group1", "maskGroup", "image8", "frame10"],
  group1: ["group1", "maskGroup", "image8"],
  maskGroup: ["maskGroup", "image8"],
  image8: ["image8"],
  frame10: ["frame10"],
  vuesaxLinearArrowRight: ["vuesaxLinearArrowRight", "vuesaxLinearArrowRight2"],
  vuesaxLinearArrowRight2: ["vuesaxLinearArrowRight2"],
  frame15: [
    "frame15",
    "frame14",
    "vuesaxLinearCalendar2",
    "vuesaxLinearCalendar22",
    "frame13",
    "vuesaxLinearClock",
    "vuesaxLinearClock2"
  ],

  frame14: ["frame14", "vuesaxLinearCalendar2", "vuesaxLinearCalendar22"],
  vuesaxLinearCalendar2: ["vuesaxLinearCalendar2", "vuesaxLinearCalendar22"],
  vuesaxLinearCalendar22: ["vuesaxLinearCalendar22"],
  frame13: ["frame13", "vuesaxLinearClock", "vuesaxLinearClock2"],
  vuesaxLinearClock: ["vuesaxLinearClock", "vuesaxLinearClock2"],
  vuesaxLinearClock2: ["vuesaxLinearClock2"],
  frame9: ["frame9", "vuesaxLinearSearchNormal", "vuesaxLinearSearchNormal2"],
  vuesaxLinearSearchNormal: [
    "vuesaxLinearSearchNormal",
    "vuesaxLinearSearchNormal2"
  ],

  vuesaxLinearSearchNormal2: ["vuesaxLinearSearchNormal2"],
  frame22: [
    "frame22",
    "frame18",
    "vuesaxBoldSun",
    "vuesaxBoldSun2",
    "frame19",
    "vuesaxBoldProfileAdd",
    "vuesaxBoldProfileAdd2",
    "frame20",
    "vuesaxBoldLink",
    "vuesaxBoldLink2",
    "link",
    "frame21",
    "vuesaxBoldHospital",
    "vuesaxBoldHospital2"
  ],

  frame18: ["frame18", "vuesaxBoldSun", "vuesaxBoldSun2"],
  vuesaxBoldSun: ["vuesaxBoldSun", "vuesaxBoldSun2"],
  vuesaxBoldSun2: ["vuesaxBoldSun2"],
  frame19: ["frame19", "vuesaxBoldProfileAdd", "vuesaxBoldProfileAdd2"],
  vuesaxBoldProfileAdd: ["vuesaxBoldProfileAdd", "vuesaxBoldProfileAdd2"],
  vuesaxBoldProfileAdd2: ["vuesaxBoldProfileAdd2"],
  frame20: ["frame20", "vuesaxBoldLink", "vuesaxBoldLink2", "link"],
  vuesaxBoldLink: ["vuesaxBoldLink", "vuesaxBoldLink2", "link"],
  vuesaxBoldLink2: ["vuesaxBoldLink2", "link"],
  link: ["link"],
  frame21: ["frame21", "vuesaxBoldHospital", "vuesaxBoldHospital2"],
  vuesaxBoldHospital: ["vuesaxBoldHospital", "vuesaxBoldHospital2"],
  vuesaxBoldHospital2: ["vuesaxBoldHospital2"],
  frame25: [
    "frame25",
    "frame33",
    "frame26",
    "frame29",
    "frame27",
    "group2",
    "maskGroup2",
    "image9",
    "frame28",
    "frame30",
    "frame32",
    "vuesaxLinearLocation",
    "vuesaxLinearLocation2",
    "frame31",
    "frame34",
    "vuesaxLinearClock3",
    "vuesaxLinearClock4",
    "frame35",
    "vuesaxLinearClock5",
    "vuesaxLinearClock6",
    "frame36",
    "frame37",
    "frame38",
    "group3",
    "maskGroup3",
    "image10",
    "frame39",
    "frame40",
    "frame41",
    "vuesaxLinearLocation3",
    "vuesaxLinearLocation4",
    "frame42",
    "frame43",
    "vuesaxLinearClock7",
    "vuesaxLinearClock8",
    "frame44",
    "vuesaxLinearClock9",
    "vuesaxLinearClock10"
  ],

  frame33: [
    "frame33",
    "frame26",
    "frame29",
    "frame27",
    "group2",
    "maskGroup2",
    "image9",
    "frame28",
    "frame30",
    "frame32",
    "vuesaxLinearLocation",
    "vuesaxLinearLocation2",
    "frame31",
    "frame34",
    "vuesaxLinearClock3",
    "vuesaxLinearClock4",
    "frame35",
    "vuesaxLinearClock5",
    "vuesaxLinearClock6",
    "frame36",
    "frame37",
    "frame38",
    "group3",
    "maskGroup3",
    "image10",
    "frame39",
    "frame40",
    "frame41",
    "vuesaxLinearLocation3",
    "vuesaxLinearLocation4",
    "frame42",
    "frame43",
    "vuesaxLinearClock7",
    "vuesaxLinearClock8",
    "frame44",
    "vuesaxLinearClock9",
    "vuesaxLinearClock10"
  ],

  frame26: [
    "frame26",
    "frame29",
    "frame27",
    "group2",
    "maskGroup2",
    "image9",
    "frame28",
    "frame30",
    "frame32",
    "vuesaxLinearLocation",
    "vuesaxLinearLocation2",
    "frame31",
    "frame34",
    "vuesaxLinearClock3",
    "vuesaxLinearClock4",
    "frame35",
    "vuesaxLinearClock5",
    "vuesaxLinearClock6"
  ],

  frame29: [
    "frame29",
    "frame27",
    "group2",
    "maskGroup2",
    "image9",
    "frame28",
    "frame30",
    "frame32",
    "vuesaxLinearLocation",
    "vuesaxLinearLocation2"
  ],

  frame27: ["frame27", "group2", "maskGroup2", "image9", "frame28", "frame30"],
  group2: ["group2", "maskGroup2", "image9"],
  maskGroup2: ["maskGroup2", "image9"],
  image9: ["image9"],
  frame28: ["frame28", "frame30"],
  frame30: ["frame30"],
  frame32: ["frame32", "vuesaxLinearLocation", "vuesaxLinearLocation2"],
  vuesaxLinearLocation: ["vuesaxLinearLocation", "vuesaxLinearLocation2"],
  vuesaxLinearLocation2: ["vuesaxLinearLocation2"],
  frame31: [
    "frame31",
    "frame34",
    "vuesaxLinearClock3",
    "vuesaxLinearClock4",
    "frame35",
    "vuesaxLinearClock5",
    "vuesaxLinearClock6"
  ],

  frame34: ["frame34", "vuesaxLinearClock3", "vuesaxLinearClock4"],
  vuesaxLinearClock3: ["vuesaxLinearClock3", "vuesaxLinearClock4"],
  vuesaxLinearClock4: ["vuesaxLinearClock4"],
  frame35: ["frame35", "vuesaxLinearClock5", "vuesaxLinearClock6"],
  vuesaxLinearClock5: ["vuesaxLinearClock5", "vuesaxLinearClock6"],
  vuesaxLinearClock6: ["vuesaxLinearClock6"],
  frame36: [
    "frame36",
    "frame37",
    "frame38",
    "group3",
    "maskGroup3",
    "image10",
    "frame39",
    "frame40",
    "frame41",
    "vuesaxLinearLocation3",
    "vuesaxLinearLocation4",
    "frame42",
    "frame43",
    "vuesaxLinearClock7",
    "vuesaxLinearClock8",
    "frame44",
    "vuesaxLinearClock9",
    "vuesaxLinearClock10"
  ],

  frame37: [
    "frame37",
    "frame38",
    "group3",
    "maskGroup3",
    "image10",
    "frame39",
    "frame40",
    "frame41",
    "vuesaxLinearLocation3",
    "vuesaxLinearLocation4"
  ],

  frame38: ["frame38", "group3", "maskGroup3", "image10", "frame39", "frame40"],
  group3: ["group3", "maskGroup3", "image10"],
  maskGroup3: ["maskGroup3", "image10"],
  image10: ["image10"],
  frame39: ["frame39", "frame40"],
  frame40: ["frame40"],
  frame41: ["frame41", "vuesaxLinearLocation3", "vuesaxLinearLocation4"],
  vuesaxLinearLocation3: ["vuesaxLinearLocation3", "vuesaxLinearLocation4"],
  vuesaxLinearLocation4: ["vuesaxLinearLocation4"],
  frame42: [
    "frame42",
    "frame43",
    "vuesaxLinearClock7",
    "vuesaxLinearClock8",
    "frame44",
    "vuesaxLinearClock9",
    "vuesaxLinearClock10"
  ],

  frame43: ["frame43", "vuesaxLinearClock7", "vuesaxLinearClock8"],
  vuesaxLinearClock7: ["vuesaxLinearClock7", "vuesaxLinearClock8"],
  vuesaxLinearClock8: ["vuesaxLinearClock8"],
  frame44: ["frame44", "vuesaxLinearClock9", "vuesaxLinearClock10"],
  vuesaxLinearClock9: ["vuesaxLinearClock9", "vuesaxLinearClock10"],
  vuesaxLinearClock10: ["vuesaxLinearClock10"],
  frame8: ["frame8", "frame7", "frame", "group"],
  frame7: ["frame7"],
  frame: ["frame", "group"],
  group: ["group"],
  statusBarIPhone1313Pro: [
    "statusBarIPhone1313Pro",
    "rightSide",
    "leftSide",
    "time"
  ],

  rightSide: ["rightSide"],
  leftSide: ["leftSide", "time"],
  time: ["time"],
  frame6: [
    "frame6",
    "frame1",
    "home2",
    "home3",
    "frame4",
    "vuesaxLinearCalendar23",
    "vuesaxLinearCalendar24",
    "frame5",
    "vuesaxLinearMessage",
    "vuesaxLinearMessage2",
    "frame3",
    "vuesaxLinearProfile",
    "vuesaxLinearProfile2"
  ],

  frame1: ["frame1", "home2", "home3"],
  home2: ["home2", "home3"],
  home3: ["home3"],
  frame4: ["frame4", "vuesaxLinearCalendar23", "vuesaxLinearCalendar24"],
  vuesaxLinearCalendar23: ["vuesaxLinearCalendar23", "vuesaxLinearCalendar24"],
  vuesaxLinearCalendar24: ["vuesaxLinearCalendar24"],
  frame5: ["frame5", "vuesaxLinearMessage", "vuesaxLinearMessage2"],
  vuesaxLinearMessage: ["vuesaxLinearMessage", "vuesaxLinearMessage2"],
  vuesaxLinearMessage2: ["vuesaxLinearMessage2"],
  frame3: ["frame3", "vuesaxLinearProfile", "vuesaxLinearProfile2"],
  vuesaxLinearProfile: ["vuesaxLinearProfile", "vuesaxLinearProfile2"],
  vuesaxLinearProfile2: ["vuesaxLinearProfile2"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicHomepage__ArgProps,
          internalVariantPropNames: PlasmicHomepage__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicHomepage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHomepage";
  } else {
    func.displayName = `PlasmicHomepage.${nodeName}`;
  }
  return func;
}

export const PlasmicHomepage = Object.assign(
  // Top-level PlasmicHomepage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    section: makeNodeComponent("section"),
    h1: makeNodeComponent("h1"),
    home: makeNodeComponent("home"),
    frame17: makeNodeComponent("frame17"),
    frame24: makeNodeComponent("frame24"),
    frame23: makeNodeComponent("frame23"),
    frame11: makeNodeComponent("frame11"),
    frame16: makeNodeComponent("frame16"),
    frame12: makeNodeComponent("frame12"),
    group1: makeNodeComponent("group1"),
    maskGroup: makeNodeComponent("maskGroup"),
    image8: makeNodeComponent("image8"),
    frame10: makeNodeComponent("frame10"),
    vuesaxLinearArrowRight: makeNodeComponent("vuesaxLinearArrowRight"),
    vuesaxLinearArrowRight2: makeNodeComponent("vuesaxLinearArrowRight2"),
    frame15: makeNodeComponent("frame15"),
    frame14: makeNodeComponent("frame14"),
    vuesaxLinearCalendar2: makeNodeComponent("vuesaxLinearCalendar2"),
    vuesaxLinearCalendar22: makeNodeComponent("vuesaxLinearCalendar22"),
    frame13: makeNodeComponent("frame13"),
    vuesaxLinearClock: makeNodeComponent("vuesaxLinearClock"),
    vuesaxLinearClock2: makeNodeComponent("vuesaxLinearClock2"),
    frame9: makeNodeComponent("frame9"),
    vuesaxLinearSearchNormal: makeNodeComponent("vuesaxLinearSearchNormal"),
    vuesaxLinearSearchNormal2: makeNodeComponent("vuesaxLinearSearchNormal2"),
    frame22: makeNodeComponent("frame22"),
    frame18: makeNodeComponent("frame18"),
    vuesaxBoldSun: makeNodeComponent("vuesaxBoldSun"),
    vuesaxBoldSun2: makeNodeComponent("vuesaxBoldSun2"),
    frame19: makeNodeComponent("frame19"),
    vuesaxBoldProfileAdd: makeNodeComponent("vuesaxBoldProfileAdd"),
    vuesaxBoldProfileAdd2: makeNodeComponent("vuesaxBoldProfileAdd2"),
    frame20: makeNodeComponent("frame20"),
    vuesaxBoldLink: makeNodeComponent("vuesaxBoldLink"),
    vuesaxBoldLink2: makeNodeComponent("vuesaxBoldLink2"),
    link: makeNodeComponent("link"),
    frame21: makeNodeComponent("frame21"),
    vuesaxBoldHospital: makeNodeComponent("vuesaxBoldHospital"),
    vuesaxBoldHospital2: makeNodeComponent("vuesaxBoldHospital2"),
    frame25: makeNodeComponent("frame25"),
    frame33: makeNodeComponent("frame33"),
    frame26: makeNodeComponent("frame26"),
    frame29: makeNodeComponent("frame29"),
    frame27: makeNodeComponent("frame27"),
    group2: makeNodeComponent("group2"),
    maskGroup2: makeNodeComponent("maskGroup2"),
    image9: makeNodeComponent("image9"),
    frame28: makeNodeComponent("frame28"),
    frame30: makeNodeComponent("frame30"),
    frame32: makeNodeComponent("frame32"),
    vuesaxLinearLocation: makeNodeComponent("vuesaxLinearLocation"),
    vuesaxLinearLocation2: makeNodeComponent("vuesaxLinearLocation2"),
    frame31: makeNodeComponent("frame31"),
    frame34: makeNodeComponent("frame34"),
    vuesaxLinearClock3: makeNodeComponent("vuesaxLinearClock3"),
    vuesaxLinearClock4: makeNodeComponent("vuesaxLinearClock4"),
    frame35: makeNodeComponent("frame35"),
    vuesaxLinearClock5: makeNodeComponent("vuesaxLinearClock5"),
    vuesaxLinearClock6: makeNodeComponent("vuesaxLinearClock6"),
    frame36: makeNodeComponent("frame36"),
    frame37: makeNodeComponent("frame37"),
    frame38: makeNodeComponent("frame38"),
    group3: makeNodeComponent("group3"),
    maskGroup3: makeNodeComponent("maskGroup3"),
    image10: makeNodeComponent("image10"),
    frame39: makeNodeComponent("frame39"),
    frame40: makeNodeComponent("frame40"),
    frame41: makeNodeComponent("frame41"),
    vuesaxLinearLocation3: makeNodeComponent("vuesaxLinearLocation3"),
    vuesaxLinearLocation4: makeNodeComponent("vuesaxLinearLocation4"),
    frame42: makeNodeComponent("frame42"),
    frame43: makeNodeComponent("frame43"),
    vuesaxLinearClock7: makeNodeComponent("vuesaxLinearClock7"),
    vuesaxLinearClock8: makeNodeComponent("vuesaxLinearClock8"),
    frame44: makeNodeComponent("frame44"),
    vuesaxLinearClock9: makeNodeComponent("vuesaxLinearClock9"),
    vuesaxLinearClock10: makeNodeComponent("vuesaxLinearClock10"),
    frame8: makeNodeComponent("frame8"),
    frame7: makeNodeComponent("frame7"),
    frame: makeNodeComponent("frame"),
    group: makeNodeComponent("group"),
    statusBarIPhone1313Pro: makeNodeComponent("statusBarIPhone1313Pro"),
    rightSide: makeNodeComponent("rightSide"),
    leftSide: makeNodeComponent("leftSide"),
    time: makeNodeComponent("time"),
    frame6: makeNodeComponent("frame6"),
    frame1: makeNodeComponent("frame1"),
    home2: makeNodeComponent("home2"),
    home3: makeNodeComponent("home3"),
    frame4: makeNodeComponent("frame4"),
    vuesaxLinearCalendar23: makeNodeComponent("vuesaxLinearCalendar23"),
    vuesaxLinearCalendar24: makeNodeComponent("vuesaxLinearCalendar24"),
    frame5: makeNodeComponent("frame5"),
    vuesaxLinearMessage: makeNodeComponent("vuesaxLinearMessage"),
    vuesaxLinearMessage2: makeNodeComponent("vuesaxLinearMessage2"),
    frame3: makeNodeComponent("frame3"),
    vuesaxLinearProfile: makeNodeComponent("vuesaxLinearProfile"),
    vuesaxLinearProfile2: makeNodeComponent("vuesaxLinearProfile2"),
    // Metadata about props expected for PlasmicHomepage
    internalVariantProps: PlasmicHomepage__VariantProps,
    internalArgProps: PlasmicHomepage__ArgProps,
    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicHomepage;
/* prettier-ignore-end */
